title: "cooking"
description: > # this means to ignore newlines until "show_excerpts:"
  if you can't handle the heat...
  
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
#minima:
#  date_format: "%b %-d, %Y"

# Build settings
theme: minima

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md



# plugins:
# - jekyll-feed
 #- jekyll-seo-tag
